//! Generates the diagnostics reference from the catalogue.
//!
//! Until this existed, `docs/gdl.md` described seventeen of the codes in a
//! hand-written table and the other fifty-seven were documented only in Rust.
//! `DiagnosticCode::title()` had no caller at all outside its own test: it was
//! declared for a reference page that was never built. This is that page.
//!
//! Run by `make diagnostics`; anti-drift is enforced by `make diagnostics-check`
//! in the build rather than by habit, exactly as `make grammar-check` does for
//! the editor's vocabulary (`cpt-gearbox-nfr-no-type-drift`, applied to the
//! documents' view of the catalogue).
//!
//! **Generated, therefore ordered by code and not by importance.** A reference
//! is looked up, not read through; the curated table in `docs/gdl.md` is where a
//! reading order lives, and it stays hand-written because it carries a column
//! -- which stage reports the code -- that the catalogue does not know.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    reason = "clippy.toml's allow-unwrap-in-tests covers `#[test]` functions but not the \
              helpers in this file; a generator that propagates errors instead of panicking \
              obscures the assertion it exists to support"
)]

use std::fmt::Write as _;
use std::path::Path;

use gearbox_ir::{DiagnosticCode, DiagnosticDomain};

const OUT: &str = "../../docs/diagnostics.md";

/// The domains, in the order their numeric ranges run.
const DOMAINS: [(DiagnosticDomain, &str, &str); 7] = [
    (
        DiagnosticDomain::Gdl,
        "GBX01xx",
        "Parsing and evaluating GDL",
    ),
    (
        DiagnosticDomain::Validate,
        "GBX02xx",
        "Cross-checking a description against Rust",
    ),
    (
        DiagnosticDomain::Topology,
        "GBX03xx",
        "Process topology and structural constraints",
    ),
    (
        DiagnosticDomain::Binding,
        "GBX04xx",
        "Contract bindings and severability",
    ),
    (
        DiagnosticDomain::Cluster,
        "GBX05xx",
        "Cluster capabilities, providers and plugins",
    ),
    (
        DiagnosticDomain::RuntimeGap,
        "GBX06xx",
        "Capabilities the runtime does not implement",
    ),
    (
        DiagnosticDomain::Generator,
        "GBX07xx",
        "Artifact generation",
    ),
];

/// A doc comment as Markdown.
///
/// `docs()` yields the lines as rustdoc stores them, each with the single
/// leading space that follows `///`. Stripping exactly one space rather than
/// trimming keeps an indented code block indented.
fn prose(code: DiagnosticCode) -> String {
    let lines: Vec<&str> = code
        .docs()
        .iter()
        .map(|line| line.strip_prefix(' ').unwrap_or(line))
        .collect();
    lines.join("\n").trim_end().to_owned()
}

/// The `prevents` reference as one readable clause, or `None`.
fn prevents(code: DiagnosticCode) -> Option<String> {
    let reference = code.prevents().as_ref()?;
    let mut rendered = format!(
        "`{}::{}` in `{}`",
        reference.ty, reference.variant, reference.krate
    );
    if let Some(canonical) = reference.canonical {
        write!(
            rendered,
            ", which travels as `{}`/`{}`",
            canonical.domain, canonical.code
        )
        .expect("write to String");
    }
    Some(rendered)
}

fn render() -> String {
    let mut out = String::new();
    out.push_str(
        "<!-- Generated by `make diagnostics`. Do not edit by hand. -->\n\n\
         # Diagnostics\n\n\
         Every diagnostic the engine can emit, from the one declaration that\n\
         defines them (`crates/gearbox-ir/src/diagnostics.rs`). A code is stable:\n\
         a retired one is never reused, so a code named in an old lock or\n\
         transcript stays findable.\n\n\
         **Severity** is the default; a call site may raise or lower it.\n\
         **Evidence** marks the codes that assert a limitation of the runtime and\n\
         must therefore cite the source proving it\n\
         (`cpt-gearbox-nfr-evidence-cited`). Every error-severity code carries a\n\
         remedy at the point it is raised\n\
         (`cpt-gearbox-nfr-actionable-diagnostics`), which is per-occurrence and\n\
         so is not listed here.\n\n",
    );

    writeln!(out, "Codes: **{}**.\n", DiagnosticCode::ALL.len()).expect("write to String");

    for (domain, range, heading) in DOMAINS {
        let codes: Vec<&DiagnosticCode> = DiagnosticCode::ALL
            .iter()
            .filter(|code| code.domain() == domain)
            .collect();
        writeln!(out, "## `{range}` — {heading}\n").expect("write to String");
        writeln!(out, "| Code | Severity | Summary |").expect("write to String");
        writeln!(out, "|---|---|---|").expect("write to String");
        for code in &codes {
            writeln!(
                out,
                "| [{}](#{}) | {} | {} |",
                code.as_str(),
                code.as_str().to_lowercase(),
                code.default_severity(),
                code.title()
            )
            .expect("write to String");
        }
        out.push('\n');

        for code in codes {
            writeln!(out, "### {}\n", code.as_str()).expect("write to String");
            writeln!(out, "**{}**\n", code.title()).expect("write to String");
            writeln!(out, "{}\n", prose(*code)).expect("write to String");
            if code.requires_evidence() {
                out.push_str(
                    "*Asserts a limitation of the runtime, so every occurrence cites the \
                     source that proves it.*\n\n",
                );
            }
            if let Some(reference) = prevents(*code) {
                writeln!(
                    out,
                    "*Prevents {reference}. The reference is resolved against the \
                     `gears-rust` checkout by `gearbox-project`'s corpus test.*\n"
                )
                .expect("write to String");
            }
        }
    }

    out
}

#[test]
fn export_diagnostics_reference() {
    let out = Path::new(env!("CARGO_MANIFEST_DIR")).join(OUT);
    let rendered = render();
    std::fs::write(&out, &rendered).expect("write diagnostics.md");

    // Spot-checks on the parts a reader would notice missing, rather than on
    // the whole shape: the file is regenerated, so its shape is not at risk --
    // what is at risk is a column silently rendering empty.
    assert!(rendered.contains("GBX0101"), "the first code is missing");
    assert!(
        rendered.contains("`RegistryError::UnknownDependency`"),
        "the `prevents` column rendered nothing"
    );
    assert!(
        rendered.contains("cluster.v1"),
        "the canonical pair rendered nothing"
    );
}

#[test]
fn every_code_reaches_the_reference() {
    // The count in the header is generated, so it cannot disagree with the
    // list. What it cannot catch is a code filtered out of every domain
    // section by a `DOMAINS` table that has fallen behind `DiagnosticDomain`.
    let rendered = render();
    for code in DiagnosticCode::ALL {
        assert!(
            rendered.contains(&format!("### {}\n", code.as_str())),
            "`{code}` has no section: is its domain listed in DOMAINS?"
        );
    }
}

#[test]
fn export_is_deterministic() {
    assert_eq!(render(), render(), "the generator is not deterministic");
}
