//! Canonical ordering, serialization, and hashing.
//!
//! `write_canonical` is where `cpt-gearbox-nfr-determinism` actually gets
//! enforced: the resolver's output only needs to be *correct*, not
//! *ordered* -- every ordering guarantee documented on [`ResolvedProduct`]'s
//! fields is imposed here, once, so a resolver bug that emits bindings in the
//! wrong order produces the same lock as one that emits them in the right
//! order. Callers that skip this module and serialize a [`ResolvedProduct`]
//! themselves get none of that guarantee.

use gearbox_ir::{ContractId, LOCK_SCHEMA_VERSION, ResolvedProduct};

use crate::error::LockError;

/// Sort every collection on `product` into the order documented on
/// [`ResolvedProduct`]'s fields, and drop the duplicate diagnostics and
/// provenance edges that resolution naturally produces (the same structural
/// fact is often reached from more than one direction).
///
/// Idempotent: canonicalizing an already-canonical product changes nothing,
/// which is what lets [`read`](crate::read) re-canonicalize a parsed lock and
/// compare its hash to the one it was written with.
pub fn canonicalize_order(product: &mut ResolvedProduct) {
    product.applications.sort_by(|a, b| a.name.cmp(&b.name));
    for application in &mut product.applications {
        application.listens.sort_by(|a, b| a.name.cmp(&b.name));
        application.spawns.sort_by(|a, b| a.gear.cmp(&b.gear));
    }

    product
        .bindings
        .sort_by(|a, b| (&a.consumer, &a.contract).cmp(&(&b.consumer, &b.contract)));

    product
        .cluster
        .sort_by(|a, b| (&a.scope, a.primitive).cmp(&(&b.scope, b.primitive)));

    product.cuttable_if_declared.sort_by(|a, b| {
        let key = |c: &gearbox_ir::CutCandidate| {
            (
                c.consumer.clone(),
                c.provider.clone(),
                c.contract
                    .as_ref()
                    .map(ContractId::as_str)
                    .unwrap_or_default()
                    .to_owned(),
            )
        };
        key(a).cmp(&key(b))
    });

    product.provenance.sort_by(|a, b| {
        (a.from.as_str(), a.kind, a.to.as_str()).cmp(&(b.from.as_str(), b.kind, b.to.as_str()))
    });
    product.provenance.dedup();

    for gear in product.gears.values_mut() {
        gear.selected_by.sort();
    }
    for binding in &mut product.cluster {
        binding.requesters.sort();
    }

    product.diagnostics.finish();
}

/// Serialize `product` to TOML with no header. Used both for the body that
/// gets hashed and, with the hash filled in, for the body that gets written.
fn to_toml(product: &ResolvedProduct) -> Result<String, LockError> {
    Ok(toml::to_string_pretty(product)?)
}

/// The hash covering everything except the hash field itself, in the
/// `blake3:<hex>` form recorded in `ResolvedProduct.product.lock_hash`.
///
/// # Errors
/// Returns [`LockError`] when the product cannot be serialized to TOML, which a
/// value the lock schema does not admit would cause.
pub fn compute_hash(canonical: &ResolvedProduct) -> Result<String, LockError> {
    let mut blanked = canonical.clone();
    blanked.product.lock_hash.clear();
    let body = to_toml(&blanked)?;
    Ok(format!("blake3:{}", blake3::hash(body.as_bytes()).to_hex()))
}

/// The two-line comment prepended to every written lock.
fn header(gearbox_version: &str) -> String {
    format!(
        "# GENERATED by gearbox {gearbox_version} -- do not edit. \
         Run `gearbox resolve` to regenerate.\n"
    )
}

/// Canonicalize, hash, and render `product` as the text of a `product.lock`
/// file.
///
/// Does not touch a filesystem -- the caller decides where the result goes,
/// and whether an existing file needs a three-way merge first (an
/// `OperatorOwned` concern that belongs to the generator, not the lock
/// format).
///
/// # Errors
/// Returns [`LockError::UnsupportedSchemaVersion`] if `product.schema_version`
/// is not one this build understands, or [`LockError::Serialize`] if the
/// product cannot be represented as TOML.
pub fn write_canonical(product: &ResolvedProduct) -> Result<String, LockError> {
    if product.schema_version != LOCK_SCHEMA_VERSION {
        return Err(LockError::UnsupportedSchemaVersion {
            found: product.schema_version,
            supported: LOCK_SCHEMA_VERSION,
        });
    }

    let mut canonical = product.clone();
    canonicalize_order(&mut canonical);

    let hash = compute_hash(&canonical)?;
    canonical.product.lock_hash = hash;

    let body = to_toml(&canonical)?;
    Ok(format!(
        "{}{body}",
        header(&canonical.product.gearbox_version)
    ))
}
