// The lock: `cpt-gearbox-fr-lock-single-source`, `cpt-gearbox-fr-lock-read-only`
// and ADR-0010 tier 1.
//
// The lock exists so that "did anything actually change" is a byte comparison
// rather than a judgement, which is why the client never renders its own TOML --
// a second serializer would be a second answer to the one question the lock
// settles.

import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

import { expect, openProduct, revealLock, test } from "../fixtures/studio";

const STUDIO_SRC = join(__dirname, "../../gearbox-studio/src");

function sources(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) return sources(path);
    return /\.tsx?$/.test(entry.name) ? [path] : [];
  });
}

async function lockShown(page: import("@playwright/test").Page) {
  return page.evaluate(() => ({
    profile: document.querySelector("[data-lock-profile]")?.getAttribute("data-lock-profile") ?? "",
    hash:
      document.querySelector("[data-lock-text-hash]")?.getAttribute("data-lock-text-hash") ?? "",
    stale: document.querySelector("[data-lock-stale]") !== null,
    text: document.querySelector("[data-lock-canonical]")?.textContent ?? "",
    resolutionHash:
      document.querySelector("[data-lock-hash]")?.getAttribute("data-lock-hash") ?? "",
  }));
}

test.describe("the lock", () => {
  test("the Lock view shows the canonical text with its generated header [plan §9: Lock]", async ({
    studio,
  }) => {
    await openProduct(studio.page, "dev");
    await revealLock(studio.page);
    const lock = await lockShown(studio.page);
    // The header is tier 2's requirement made visible: a generated file says so
    // in its first line, and that line is what stands between tier 2 and tier 5.
    expect(lock.text.split("\n")[0]).toMatch(/^# GENERATED by gearbox .* do not edit/);
    expect(lock.text).toContain("schema_version = 1");
    expect(lock.text.split("\n").length).toBeGreaterThan(100);
  });

  test("the lock's own hash matches the resolution on screen [plan §9: lock_hash badge]", async ({
    studio,
  }) => {
    await openProduct(studio.page, "dev");
    await revealLock(studio.page);
    const lock = await lockShown(studio.page);
    expect(lock.hash).toMatch(/^blake3:/);
    // Both come from the same resolution, so a mismatch would mean the two
    // answers on screen are about different runs. The badge says so when they
    // disagree; this asserts they do not.
    expect(lock.stale).toBe(false);
    expect(lock.text).toContain(lock.hash);
  });

  test("each profile has its own lock text [PRD cpt-gearbox-fr-lock-single-source]", async ({
    studio,
  }) => {
    await openProduct(studio.page, "dev");
    await revealLock(studio.page);
    const dev = await lockShown(studio.page);

    await openProduct(studio.page, "prod");
    await revealLock(studio.page);
    const prod = await lockShown(studio.page);

    expect(dev.profile).toBe("dev");
    expect(prod.profile).toBe("prod");
    expect(prod.hash).not.toBe(dev.hash);
    expect(prod.text).not.toBe(dev.text);
    // Not just different bytes -- different in the way the profile implies.
    expect(dev.text).toContain('profile_kind = "embedded"');
    expect(prod.text).toContain('profile_kind = "kubernetes"');
  });

  test("the client never serializes a lock of its own [PRD cpt-gearbox-fr-lock-single-source]", () => {
    // `gearbox_lock::write_canonical` is the one function that decides the lock's
    // bytes, and the frontend asks for its output rather than producing
    // equivalent text. A TOML writer in here would be a second answer, and byte
    // identity across runs is the property the lock exists for.
    const offenders = sources(STUDIO_SRC).filter((file) => {
      const text = readFileSync(file, "utf8");
      return /\btoml\b/i.test(text) && !/generated|write_canonical|no TOML grammar/i.test(text);
    });
    expect(offenders).toEqual([]);
  });

  test.fixme("the Lock view diffs against the lock on disk [plan §9: diff toggle vs disk]", async ({
    studio,
  }) => {
    // Blocked on the same thing: nothing on the wire says where the lock was
    // written, so there is no on-disk text to diff against. The stale badge that
    // §9 pairs with this is implemented for the comparison that *is* available --
    // the lock text's hash against the resolution's.
    await openProduct(studio.page, "dev");
    await revealLock(studio.page);
    await expect(studio.page.locator("[data-lock-diff]")).toBeVisible();
  });
});
