// The lock: `cpt-gearbox-fr-lock-single-source`, `cpt-gearbox-fr-lock-read-only`
// and ADR-0010 tier 1.
//
// The lock exists so that "did anything actually change" is a byte comparison
// rather than a judgement, which is why the client never renders its own TOML --
// a second serializer would be a second answer to the one question the lock
// settles.

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import {
  expect,
  openProduct,
  openProductById,
  revealLock,
  revealLockView,
  settled,
  test,
} from "../fixtures/studio";
import { copyProduct, type ProductCopy } from "../fixtures/product-copy";

const STUDIO_SRC = join(__dirname, "../../gearbox-studio/src");
const REPO = join(__dirname, "../../..");

function sources(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) return sources(path);
    return /\.tsx?$/.test(entry.name) ? [path] : [];
  });
}

async function lockShown(page: import("@playwright/test").Page) {
  return page.evaluate(() => ({
    profile: document.querySelector("[data-lock-profile]")?.getAttribute("data-lock-profile") ?? "",
    hash:
      document.querySelector("[data-lock-text-hash]")?.getAttribute("data-lock-text-hash") ?? "",
    stale: document.querySelector("[data-lock-stale]") !== null,
    text: document.querySelector("[data-lock-canonical]")?.textContent ?? "",
    resolutionHash:
      document.querySelector("[data-lock-hash]")?.getAttribute("data-lock-hash") ?? "",
  }));
}

test.describe("the lock", () => {
  test("the Lock view shows the canonical text with its generated header [plan §9: Lock]", async ({
    studio,
  }) => {
    await openProduct(studio.page, "dev");
    await revealLock(studio.page);
    const lock = await lockShown(studio.page);
    // The header is tier 2's requirement made visible: a generated file says so
    // in its first line, and that line is what stands between tier 2 and tier 5.
    expect(lock.text.split("\n")[0]).toMatch(/^# GENERATED by gearbox .* do not edit/);
    expect(lock.text).toContain("schema_version = 1");
    expect(lock.text.split("\n").length).toBeGreaterThan(100);
  });

  test("the lock's own hash matches the resolution on screen [plan §9: lock_hash badge]", async ({
    studio,
  }) => {
    await openProduct(studio.page, "dev");
    await revealLock(studio.page);
    // Refreshed before reading, for the reason the last test in this file gives:
    // the store fetches the lock once per resolution and nothing watches the
    // file, so a comparison established by an earlier spec is still on screen.
    // Without this the assertion passes alone and fails in a full run -- which
    // is not the claim disagreeing, it is the claim reading someone else's
    // answer.
    await studio.page.locator("[data-lock-refresh]").click();
    // The refresh re-fetches, so the widget is momentarily empty. Waiting for
    // the hash to come back is what makes the read below about the new answer
    // rather than about whatever was on screen mid-flight.
    await expect(studio.page.locator("[data-lock-text-hash]")).toHaveAttribute(
      "data-lock-text-hash",
      /^blake3:/,
      { timeout: 30_000 },
    );
    const lock = await lockShown(studio.page);
    expect(lock.hash).toMatch(/^blake3:/);
    // Both come from the same resolution, so a mismatch would mean the two
    // answers on screen are about different runs. The badge says so when they
    // disagree; this asserts they do not.
    expect(lock.stale).toBe(false);
    expect(lock.text).toContain(lock.hash);
  });

  test("each profile has its own lock text [PRD cpt-gearbox-fr-lock-single-source]", async ({
    studio,
  }) => {
    await openProduct(studio.page, "dev");
    await revealLock(studio.page);
    const dev = await lockShown(studio.page);

    await openProduct(studio.page, "prod");
    await revealLock(studio.page);
    const prod = await lockShown(studio.page);

    expect(dev.profile).toBe("dev");
    expect(prod.profile).toBe("prod");
    expect(prod.hash).not.toBe(dev.hash);
    expect(prod.text).not.toBe(dev.text);
    // Not just different bytes -- different in the way the profile implies.
    expect(dev.text).toContain('profile_kind = "embedded"');
    expect(prod.text).toContain('profile_kind = "kubernetes"');
  });

  test("the client never serializes a lock of its own [PRD cpt-gearbox-fr-lock-single-source]", () => {
    // `gearbox_lock::write_canonical` is the one function that decides the lock's
    // bytes, and the frontend asks for its output rather than producing
    // equivalent text. A TOML writer in here would be a second answer, and byte
    // identity across runs is the property the lock exists for.
    const offenders = sources(STUDIO_SRC).filter((file) => {
      const text = readFileSync(file, "utf8");
      return /\btoml\b/i.test(text) && !/generated|write_canonical|no TOML grammar/i.test(text);
    });
    expect(offenders).toEqual([]);
  });

  /**
   * A product of this claim's own, with a lock it generated itself.
   *
   * **These three claims used to borrow the lock `global-setup` primes for
   * `payments-demo/dev`.** Two of them overwrote it and restored it from a
   * snapshot; the third needed it pristine and, when it was not, skipped. All of
   * that happened inside `.gearbox/`, which is gitignored -- so no guard in this
   * suite could see a restore that failed, in this run or any later one, and the
   * failure mode reported itself as "1 skipped".
   *
   * A private copy removes the sharing rather than tightening the restore: the
   * lock is generated seconds before it is read, so the matching case is an
   * assertion instead of a hope, and nothing needs putting back.
   */
  const copies = new Map<string, { copy: ProductCopy; lock: string }>();

  // **Made before any page loads, and read by a fresh one.**
  // `ProductStore.ensureDiscovered` returns early once it holds a list, so a
  // product created after a page booted is never offered by `Open Product…` in
  // that page. `beforeAll` runs before the test-scoped fixtures resolve, so the
  // copies exist by the time `freshStudio` boots and discovers them.
  test.beforeAll(() => {
    for (const slug of ["lock-drift", "lock-tamper", "lock-current"]) {
      const copy = copyProduct(REPO, "payments-demo", slug);
      copies.set(slug, { copy, lock: copy.generate("dev") });
    }
  });

  test.afterAll(() => {
    for (const { copy } of copies.values()) copy.dispose();
    copies.clear();
  });

  function privateLock(slug: string): { copy: ProductCopy; lock: string } {
    const made = copies.get(slug);
    if (made === undefined) throw new Error(`no copy was made for ${slug}`);
    return made;
  }

  test("the Lock view diffs against the lock on disk [plan §9: diff toggle vs disk]", async ({
    freshStudio,
  }) => {
    // The difference is *made*, not waited for: a healthy tree's `dev` lock
    // matches, so a test that reported whichever state it found would assert the
    // trivial branch and leave the change list and the toggle unexercised.
    //
    // The stale lock is the **`prod`** one, taken from the view itself. It has to
    // be a real lock, because `read` verifies the hash and `diff` compares two
    // *parsed* locks -- which is the whole point of this view over a text diff.
    // Editing a line instead produces a hash mismatch, a different state, tested
    // below. The file is gitignored and regenerable, and the bytes go back in
    // `finally`.
    //
    // None of this could be honest until the source digest became content-based:
    // a lock written by the CLI carried that client's spelling of the source root
    // and therefore a different hash, so every CLI-written lock would have read as
    // stale here forever.
    const { copy, lock } = privateLock("lock-drift");

    try {
      await openProductById(freshStudio.page, copy.id, "prod");
      await revealLock(freshStudio.page);
      const prod = await freshStudio.page.locator("[data-lock-canonical]").textContent();
      expect(prod ?? "").toContain("# GENERATED by gearbox");
      writeFileSync(lock, prod ?? "");

      await openProductById(freshStudio.page, copy.id, "dev");
      await revealLock(freshStudio.page);
      // The store fetches the lock once per resolution and nothing watches
      // `.gearbox/**`, so the file that changed behind it has to be re-read. This
      // is the control a person uses after running `gearbox generate` in a
      // terminal, so exercising it here is not a workaround.
      await freshStudio.page.locator("[data-lock-refresh]").click();

      const disk = freshStudio.page.locator("[data-lock-disk]");
      await expect(disk).toHaveAttribute("data-lock-disk", "drifted");
      // The path in every state: "nothing on disk" and "I looked somewhere else"
      // are indistinguishable without it.
      // The path is the copy's, which is the point: a generated tree is keyed on
      // the id the description declares, so naming `payments-demo` here would
      // have passed only while this claim shared that product's lock.
      await expect(disk.locator("code").first()).toContainText(`.gearbox/${copy.id}/dev`);

      // The engine's own words, marked `+`/`-`/`~`. Structured, not textual: it
      // names the profile that changed, which a line diff cannot.
      const changes = disk.locator(".gbx-lock-changes li");
      await expect(changes.first()).toContainText("profile: prod -> dev");
      await expect(changes.first()).toHaveAttribute("data-lock-change", "~");
      expect(await changes.count()).toBeGreaterThan(1);

      // By `[data-lock-showing]`, not `.gbx-lock-toggle`: the re-read control
      // shares that class, legitimately -- both are the same kind of small button
      // -- so the class styles and the attribute identifies.
      const toggle = disk.locator("[data-lock-showing]");
      await expect(toggle).toHaveAttribute("data-lock-showing", "resolved");
      await expect(freshStudio.page.locator("[data-lock-canonical]")).toContainText('profile = "dev"');
      await toggle.click();
      await expect(toggle).toHaveAttribute("data-lock-showing", "disk");
      await expect(freshStudio.page.locator("[data-lock-canonical]")).toContainText('profile = "prod"');
    } finally {
      // Nothing to put back: the product and its generated tree are this
      // claim's, and `afterAll` takes them.
      void copy;
    }
  });

  test("a tampered lock is neither current nor stale [plan §9: diff toggle vs disk]", async ({
    freshStudio,
  }) => {
    // `gearbox_lock::read` recomputes the hash and refuses on a mismatch, so a
    // lock is self-verifying. That makes "there is a file and it does not verify"
    // a fourth state, distinct from current, drifted and absent -- and reporting
    // an empty diff for it, which is what a text comparison would do, would say
    // the opposite of the truth.
    const { copy, lock } = privateLock("lock-tamper");

    try {
      const generated = readFileSync(lock, "utf8");
      writeFileSync(
        lock,
        generated.replace(/^lock_hash = "blake3:[0-9a-f]+"$/m, 'lock_hash = "blake3:00"'),
      );
      await openProductById(freshStudio.page, copy.id, "dev");
      await revealLock(freshStudio.page);
      await freshStudio.page.locator("[data-lock-refresh]").click();

      const disk = freshStudio.page.locator("[data-lock-disk]");
      await expect(disk).toHaveAttribute("data-lock-disk", "unreadable");
      await expect(disk).toContainText("blake3:00");
      await expect(disk.locator(".gbx-lock-changes")).toHaveCount(0);
    } finally {
      void copy;
    }
  });

  test("a lock that matches the disk says so, without a toggle [plan §9: lock_hash badge]", async ({
    freshStudio,
  }) => {
    // The state a healthy tree is in, and it needs its own test: a control that
    // switches between two identical texts is worse than no control, so its
    // absence is the assertion.
    // **Asserted, not skipped.** This read whichever lock the run happened to
    // leave on disk and, when it was not the matching one, skipped -- so the two
    // claims above failing to restore reported itself as "1 skipped" and the
    // state this claim exists for went unobserved. Its lock is generated from
    // its own description a moment ago, so `current` is a fact about the code
    // rather than about what ran before.
    const { copy } = privateLock("lock-current");

    try {
      await openProductById(freshStudio.page, copy.id, "dev");
      await revealLock(freshStudio.page);
      // Nothing watches `.gearbox/**`, so a comparison cached from another
      // resolution is about bytes that are no longer the ones on disk.
      await freshStudio.page.locator("[data-lock-refresh]").click();
      const disk = freshStudio.page.locator("[data-lock-disk]");
      await expect(disk).toHaveAttribute("data-lock-disk", "current");
      await expect(disk.locator("[data-lock-current]")).toBeVisible();
      await expect(disk.locator("[data-lock-showing]")).toHaveCount(0);
    } finally {
      void copy;
    }
  });

  test("the lock opens on a summary, with the canonical text one click away [plan §9: Lock]", async ({
    freshStudio,
  }) => {
    // A UX pass described this view as a useful header followed by a wall of
    // TOML. Both halves are wanted -- comparing the canonical text against one in
    // a terminal is a real thing people do -- but the several-hundred-line text
    // answers the second question, not the first.
    //
    // The summary is counted from `ResolvedProduct`, the same object the header's
    // hash comes from. It is deliberately not parsed out of the canonical text:
    // this file's own claim greps the Studio source for a TOML reader, and a
    // second opinion about a file the engine just wrote is exactly what that
    // forbids.
    // `freshStudio`, because "opens on" is a claim about a view nobody has
    // touched: the widget remembers which half a person chose, which is right
    // behaviour and makes the shared session the wrong place to ask.
    const { page } = freshStudio;
    await settled(page);
    await openProduct(page, "dev");
    await revealLockView(page);

    const summary = page.locator('[data-lock-summary="ready"]');
    await expect(summary).toBeVisible({ timeout: 60_000 });
    await expect(page.locator("[data-lock-canonical]")).toHaveCount(0);
    await expect(summary.locator('[data-lock-summary-count="gears"]')).not.toHaveText("0");
    await expect(summary.locator("[data-lock-summary-application]").first()).toBeVisible();

    await page.locator('[data-lock-tab="raw"]').click();
    await expect(page.locator("[data-lock-canonical]")).toContainText("GENERATED by gearbox");
  });
});
