// The lock: `cpt-gearbox-fr-lock-single-source`, `cpt-gearbox-fr-lock-read-only`
// and ADR-0010 tier 1.
//
// The lock exists so that "did anything actually change" is a byte comparison
// rather than a judgement, which is why the client never renders its own TOML --
// a second serializer would be a second answer to the one question the lock
// settles.

import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { expect, openProduct, revealLock, test } from "../fixtures/studio";

const STUDIO_SRC = join(__dirname, "../../gearbox-studio/src");
const REPO = join(__dirname, "../../..");

function sources(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) return sources(path);
    return /\.tsx?$/.test(entry.name) ? [path] : [];
  });
}

async function lockShown(page: import("@playwright/test").Page) {
  return page.evaluate(() => ({
    profile: document.querySelector("[data-lock-profile]")?.getAttribute("data-lock-profile") ?? "",
    hash:
      document.querySelector("[data-lock-text-hash]")?.getAttribute("data-lock-text-hash") ?? "",
    stale: document.querySelector("[data-lock-stale]") !== null,
    text: document.querySelector("[data-lock-canonical]")?.textContent ?? "",
    resolutionHash:
      document.querySelector("[data-lock-hash]")?.getAttribute("data-lock-hash") ?? "",
  }));
}

test.describe("the lock", () => {
  test("the Lock view shows the canonical text with its generated header [plan §9: Lock]", async ({
    studio,
  }) => {
    await openProduct(studio.page, "dev");
    await revealLock(studio.page);
    const lock = await lockShown(studio.page);
    // The header is tier 2's requirement made visible: a generated file says so
    // in its first line, and that line is what stands between tier 2 and tier 5.
    expect(lock.text.split("\n")[0]).toMatch(/^# GENERATED by gearbox .* do not edit/);
    expect(lock.text).toContain("schema_version = 1");
    expect(lock.text.split("\n").length).toBeGreaterThan(100);
  });

  test("the lock's own hash matches the resolution on screen [plan §9: lock_hash badge]", async ({
    studio,
  }) => {
    await openProduct(studio.page, "dev");
    await revealLock(studio.page);
    // Refreshed before reading, for the reason the last test in this file gives:
    // the store fetches the lock once per resolution and nothing watches the
    // file, so a comparison established by an earlier spec is still on screen.
    // Without this the assertion passes alone and fails in a full run -- which
    // is not the claim disagreeing, it is the claim reading someone else's
    // answer.
    await studio.page.locator("[data-lock-refresh]").click();
    // The refresh re-fetches, so the widget is momentarily empty. Waiting for
    // the hash to come back is what makes the read below about the new answer
    // rather than about whatever was on screen mid-flight.
    await expect(studio.page.locator("[data-lock-text-hash]")).toHaveAttribute(
      "data-lock-text-hash",
      /^blake3:/,
      { timeout: 30_000 },
    );
    const lock = await lockShown(studio.page);
    expect(lock.hash).toMatch(/^blake3:/);
    // Both come from the same resolution, so a mismatch would mean the two
    // answers on screen are about different runs. The badge says so when they
    // disagree; this asserts they do not.
    expect(lock.stale).toBe(false);
    expect(lock.text).toContain(lock.hash);
  });

  test("each profile has its own lock text [PRD cpt-gearbox-fr-lock-single-source]", async ({
    studio,
  }) => {
    await openProduct(studio.page, "dev");
    await revealLock(studio.page);
    const dev = await lockShown(studio.page);

    await openProduct(studio.page, "prod");
    await revealLock(studio.page);
    const prod = await lockShown(studio.page);

    expect(dev.profile).toBe("dev");
    expect(prod.profile).toBe("prod");
    expect(prod.hash).not.toBe(dev.hash);
    expect(prod.text).not.toBe(dev.text);
    // Not just different bytes -- different in the way the profile implies.
    expect(dev.text).toContain('profile_kind = "embedded"');
    expect(prod.text).toContain('profile_kind = "kubernetes"');
  });

  test("the client never serializes a lock of its own [PRD cpt-gearbox-fr-lock-single-source]", () => {
    // `gearbox_lock::write_canonical` is the one function that decides the lock's
    // bytes, and the frontend asks for its output rather than producing
    // equivalent text. A TOML writer in here would be a second answer, and byte
    // identity across runs is the property the lock exists for.
    const offenders = sources(STUDIO_SRC).filter((file) => {
      const text = readFileSync(file, "utf8");
      return /\btoml\b/i.test(text) && !/generated|write_canonical|no TOML grammar/i.test(text);
    });
    expect(offenders).toEqual([]);
  });

  /** The lock the Generate view writes for `dev`, which these tests borrow. */
  const DEV_LOCK = join(REPO, ".gearbox/payments-demo/dev/product.lock");

  test("the Lock view diffs against the lock on disk [plan §9: diff toggle vs disk]", async ({
    studio,
  }) => {
    // The difference is *made*, not waited for: a healthy tree's `dev` lock
    // matches, so a test that reported whichever state it found would assert the
    // trivial branch and leave the change list and the toggle unexercised.
    //
    // The stale lock is the **`prod`** one, taken from the view itself. It has to
    // be a real lock, because `read` verifies the hash and `diff` compares two
    // *parsed* locks -- which is the whole point of this view over a text diff.
    // Editing a line instead produces a hash mismatch, a different state, tested
    // below. The file is gitignored and regenerable, and the bytes go back in
    // `finally`.
    //
    // None of this could be honest until the source digest became content-based:
    // a lock written by the CLI carried that client's spelling of the source root
    // and therefore a different hash, so every CLI-written lock would have read as
    // stale here forever.
    test.skip(!existsSync(DEV_LOCK), "no generated lock on disk to compare against");
    const original = readFileSync(DEV_LOCK, "utf8");

    try {
      await openProduct(studio.page, "prod");
      await revealLock(studio.page);
      const prod = await studio.page.locator("[data-lock-canonical]").textContent();
      expect(prod ?? "").toContain("# GENERATED by gearbox");
      writeFileSync(DEV_LOCK, prod ?? "");

      await openProduct(studio.page, "dev");
      await revealLock(studio.page);
      // The store fetches the lock once per resolution and nothing watches
      // `.gearbox/**`, so the file that changed behind it has to be re-read. This
      // is the control a person uses after running `gearbox generate` in a
      // terminal, so exercising it here is not a workaround.
      await studio.page.locator("[data-lock-refresh]").click();

      const disk = studio.page.locator("[data-lock-disk]");
      await expect(disk).toHaveAttribute("data-lock-disk", "drifted");
      // The path in every state: "nothing on disk" and "I looked somewhere else"
      // are indistinguishable without it.
      await expect(disk.locator("code").first()).toContainText(".gearbox/payments-demo/dev");

      // The engine's own words, marked `+`/`-`/`~`. Structured, not textual: it
      // names the profile that changed, which a line diff cannot.
      const changes = disk.locator(".gbx-lock-changes li");
      await expect(changes.first()).toContainText("profile: prod -> dev");
      await expect(changes.first()).toHaveAttribute("data-lock-change", "~");
      expect(await changes.count()).toBeGreaterThan(1);

      // By `[data-lock-showing]`, not `.gbx-lock-toggle`: the re-read control
      // shares that class, legitimately -- both are the same kind of small button
      // -- so the class styles and the attribute identifies.
      const toggle = disk.locator("[data-lock-showing]");
      await expect(toggle).toHaveAttribute("data-lock-showing", "resolved");
      await expect(studio.page.locator("[data-lock-canonical]")).toContainText('profile = "dev"');
      await toggle.click();
      await expect(toggle).toHaveAttribute("data-lock-showing", "disk");
      await expect(studio.page.locator("[data-lock-canonical]")).toContainText('profile = "prod"');
    } finally {
      writeFileSync(DEV_LOCK, original);
    }
  });

  test("a tampered lock is neither current nor stale [plan §9: diff toggle vs disk]", async ({
    studio,
  }) => {
    // `gearbox_lock::read` recomputes the hash and refuses on a mismatch, so a
    // lock is self-verifying. That makes "there is a file and it does not verify"
    // a fourth state, distinct from current, drifted and absent -- and reporting
    // an empty diff for it, which is what a text comparison would do, would say
    // the opposite of the truth.
    test.skip(!existsSync(DEV_LOCK), "no generated lock on disk to compare against");
    const original = readFileSync(DEV_LOCK, "utf8");

    try {
      writeFileSync(
        DEV_LOCK,
        original.replace(/^lock_hash = "blake3:[0-9a-f]+"$/m, 'lock_hash = "blake3:00"'),
      );
      await openProduct(studio.page, "dev");
      await revealLock(studio.page);
      await studio.page.locator("[data-lock-refresh]").click();

      const disk = studio.page.locator("[data-lock-disk]");
      await expect(disk).toHaveAttribute("data-lock-disk", "unreadable");
      await expect(disk).toContainText("blake3:00");
      await expect(disk.locator(".gbx-lock-changes")).toHaveCount(0);
    } finally {
      writeFileSync(DEV_LOCK, original);
    }
  });

  test("a lock that matches the disk says so, without a toggle [plan §9: lock_hash badge]", async ({
    studio,
  }) => {
    // The state a healthy tree is in, and it needs its own test: a control that
    // switches between two identical texts is worse than no control, so its
    // absence is the assertion.
    test.skip(!existsSync(DEV_LOCK), "no generated lock on disk to compare against");

    await openProduct(studio.page, "dev");
    await revealLock(studio.page);
    // A previous test in this file restored the file behind the store's back, so
    // the cached comparison is about bytes that are no longer there.
    await studio.page.locator("[data-lock-refresh]").click();
    const disk = studio.page.locator("[data-lock-disk]");
    const state = await disk.getAttribute("data-lock-disk");
    test.skip(
      state !== "current",
      `the lock on disk reads \`${state}\`; regenerate it to observe the matching case`,
    );

    await expect(disk.locator("[data-lock-current]")).toBeVisible();
    await expect(disk.locator("[data-lock-showing]")).toHaveCount(0);
  });
});
