//! Helm umbrella chart: one subchart per process.
//!
//! Emitted only for a Kubernetes profile. Chart.yaml and values.yaml are
//! serialized data, not templates -- minijinja would turn a version string
//! into an accidental substitution, and "Template text. Serialize data" is
//! the rule this milestone exists to keep. The YAML *inside* `templates/`
//! is Helm, so minijinja runs with `<< >>` delimiters and leaves `{{ }}`
//! for Helm.
//!
//! Service names are the process/subchart names, not Helm fullnames.
//! `advertise_uri` in the lock is `http://{subchart}.{namespace}.svc...`;
//! a Service named `{release}-{name}` would be a DNS name nobody dials.
//! The cluster SDK is stricter still: if the process links the `cluster`
//! gear, a second Service is named exactly `cluster` on port 50051.

use std::collections::BTreeMap;

use gearbox_ir::{FileEntry, FileKind, FileSet, Ownership, ProcessKind, ResolvedProcess};
use minijinja::context;
use serde::Serialize;

use super::paths;
use super::templates;
use super::{GenerateError, GenerateInput, K8S_HOME_DIR, NONROOT_UID, header};

const CLUSTER_SERVICE: &str = "cluster";
const CLUSTER_PORT: u16 = 50051;

#[derive(Serialize)]
struct NamedPort {
    name: String,
    port: u16,
}

/// Every Helm artefact for this lock, or none if the profile does not
/// generate a chart.
///
/// Reads each process's already-generated `config/<p>.yaml` out of `files`
/// so the `ConfigMap` carries the same bytes the binary will `--config`.
///
/// # Errors
/// Returns [`GenerateError`] when a template cannot render, a path is not
/// a valid relative path, or a process has no image under Kubernetes.
pub fn files(input: &GenerateInput<'_>, files: &FileSet) -> Result<Vec<FileEntry>, GenerateError> {
    if input.lock.kubernetes.is_none() {
        return Ok(Vec::new());
    }

    let product = input.lock.product.id.as_str();
    let version = input.lock.product.version.as_str();
    let mut out = Vec::new();

    out.push(umbrella_chart(input, product, version)?);
    out.push(umbrella_values(input)?);
    out.push(umbrella_helpers(product)?);

    for process in &input.lock.processes {
        let sub = subchart_name(process);
        out.push(subchart_chart(product, sub, version)?);
        out.extend(subchart_templates(input, process, files)?);
    }
    Ok(out)
}

fn subchart_name(process: &ResolvedProcess) -> &str {
    process
        .subchart
        .as_deref()
        .unwrap_or_else(|| process.name.as_str())
}

fn umbrella_chart(
    input: &GenerateInput<'_>,
    product: &str,
    version: &str,
) -> Result<FileEntry, GenerateError> {
    let mut body = String::new();
    body.push_str(&header("#"));
    body.push_str("apiVersion: v2\n");
    body.push_str("name: ");
    body.push_str(product);
    body.push('\n');
    body.push_str("description: Generated gearbox chart; workloads live in charts/\n");
    body.push_str("type: application\n");
    body.push_str("version: \"");
    body.push_str(version);
    body.push_str("\"\n");
    body.push_str("appVersion: \"");
    body.push_str(version);
    body.push_str("\"\n");
    body.push_str("dependencies:\n");
    for process in &input.lock.processes {
        let sub = subchart_name(process);
        body.push_str("  - name: ");
        body.push_str(sub);
        body.push('\n');
        body.push_str("    version: \"");
        body.push_str(version);
        body.push_str("\"\n");
        body.push_str("    repository: \"file://charts/");
        body.push_str(sub);
        body.push_str("\"\n");
        body.push_str("    condition: ");
        body.push_str(sub);
        body.push_str(".enabled\n");
    }
    Ok(FileEntry::text(
        paths::rel(&["helm", product, "Chart.yaml"])?,
        body,
        FileKind::Yaml,
        Ownership::Generated,
    ))
}

fn subchart_chart(product: &str, sub: &str, version: &str) -> Result<FileEntry, GenerateError> {
    let mut body = String::new();
    body.push_str(&header("#"));
    body.push_str("apiVersion: v2\n");
    body.push_str("name: ");
    body.push_str(sub);
    body.push('\n');
    body.push_str("description: Process subchart generated by gearbox\n");
    body.push_str("type: application\n");
    body.push_str("version: \"");
    body.push_str(version);
    body.push_str("\"\n");
    body.push_str("appVersion: \"");
    body.push_str(version);
    body.push_str("\"\n");
    Ok(FileEntry::text(
        paths::rel(&["helm", product, "charts", sub, "Chart.yaml"])?,
        body,
        FileKind::Yaml,
        Ownership::Generated,
    ))
}

/// Umbrella values: one block per subchart, keyed by subchart name so
/// `condition: <sub>.enabled` has something to read.
fn umbrella_values(input: &GenerateInput<'_>) -> Result<FileEntry, GenerateError> {
    let mut blocks = BTreeMap::new();
    for process in &input.lock.processes {
        let (repository, tag) = split_image(process.image.as_deref().unwrap_or(&process.bin_name));
        let mut block = BTreeMap::new();
        block.insert("enabled".to_owned(), serde_json::Value::Bool(true));
        block.insert(
            "replicaCount".to_owned(),
            serde_json::Value::from(process.replicas),
        );
        block.insert(
            "image".to_owned(),
            serde_json::json!({
                "repository": repository,
                "tag": tag,
                "pullPolicy": "IfNotPresent",
            }),
        );
        block.insert(
            "serviceAccount".to_owned(),
            serde_json::json!({ "create": true }),
        );
        blocks.insert(
            subchart_name(process).to_owned(),
            serde_json::Value::Object(block.into_iter().collect()),
        );
    }
    let yaml = serde_saphyr::to_string(&blocks).map_err(|source| GenerateError::Yaml {
        what: "helm values.yaml",
        source,
    })?;
    Ok(FileEntry::text(
        paths::rel(&["helm", input.lock.product.id.as_str(), "values.yaml"])?,
        format!("{}\n{yaml}", header("#")),
        FileKind::Yaml,
        Ownership::Generated,
    ))
}

fn umbrella_helpers(product: &str) -> Result<FileEntry, GenerateError> {
    Ok(FileEntry::text(
        paths::rel(&["helm", product, "templates", "_helpers.tpl"])?,
        format!(
            "{{{{/* GENERATED by gearbox {} -- do not edit. Workloads live in charts/. */}}}}\n",
            env!("CARGO_PKG_VERSION")
        ),
        FileKind::Text,
        Ownership::Generated,
    ))
}

fn subchart_templates(
    input: &GenerateInput<'_>,
    process: &ResolvedProcess,
    files: &FileSet,
) -> Result<Vec<FileEntry>, GenerateError> {
    let product = input.lock.product.id.as_str();
    let name = subchart_name(process);
    let config_filename = format!("{}.yaml", process.name);
    let config_rel = paths::rel(&["config", &config_filename])?;
    let config_raw = files
        .get(&config_rel)
        .and_then(FileEntry::as_text)
        .ok_or_else(|| GenerateError::BadPath {
            path: config_rel.as_str().to_owned(),
        })?;
    let config_yaml = indent_block(config_raw, 4);

    let ports = named_ports(process);
    let http_port = process
        .service_port
        .or_else(|| ports.first().map(|p| p.port))
        .unwrap_or(80);
    let prefix = rest_prefix(input, process);
    let liveness_path = probe_path(&prefix, "/healthz");
    let readiness_path = probe_path(&prefix, "/readyz");
    let cluster_service = process.gears.iter().any(|g| g.as_str() == CLUSTER_SERVICE);

    let common = context! {
        name => name,
        process => process.name.as_str(),
        uid => NONROOT_UID,
    };

    let helpers = templates::render_helm(
        "helm/helpers.tpl",
        input.templates.get("helm/helpers.tpl")?,
        common,
    )?;
    let deployment = templates::render_helm(
        "helm/deployment.yaml",
        input.templates.get("helm/deployment.yaml")?,
        context! {
            name => name,
            process => process.name.as_str(),
            config_filename => config_filename.as_str(),
            http_port => http_port,
            liveness_path => liveness_path.as_str(),
            readiness_path => readiness_path.as_str(),
            uid => NONROOT_UID,
            home_dir => K8S_HOME_DIR,
            container_ports => &ports,
        },
    )?;
    let service = templates::render_helm(
        "helm/service.yaml",
        input.templates.get("helm/service.yaml")?,
        context! {
            name => name,
            service_name => name,
            ports => &ports,
            cluster_service => cluster_service,
            cluster_port => CLUSTER_PORT,
        },
    )?;
    let configmap = templates::render_helm(
        "helm/configmap.yaml",
        input.templates.get("helm/configmap.yaml")?,
        context! {
            name => name,
            config_filename => config_filename.as_str(),
            config_yaml => config_yaml.as_str(),
        },
    )?;
    let serviceaccount = templates::render_helm(
        "helm/serviceaccount.yaml",
        input.templates.get("helm/serviceaccount.yaml")?,
        context! { name => name },
    )?;

    let base = |file: &str| -> Result<_, GenerateError> {
        paths::rel(&["helm", product, "charts", name, "templates", file])
    };
    Ok(vec![
        FileEntry::text(
            base("_helpers.tpl")?,
            helpers,
            FileKind::Text,
            Ownership::Generated,
        ),
        FileEntry::text(
            base("deployment.yaml")?,
            deployment,
            FileKind::Yaml,
            Ownership::Generated,
        ),
        FileEntry::text(
            base("service.yaml")?,
            service,
            FileKind::Yaml,
            Ownership::Generated,
        ),
        FileEntry::text(
            base("configmap.yaml")?,
            configmap,
            FileKind::Yaml,
            Ownership::Generated,
        ),
        FileEntry::text(
            base("serviceaccount.yaml")?,
            serviceaccount,
            FileKind::Yaml,
            Ownership::Generated,
        ),
    ])
}

fn indent_block(text: &str, spaces: usize) -> String {
    let pad = " ".repeat(spaces);
    let mut out = String::new();
    for (i, line) in text.lines().enumerate() {
        if i > 0 {
            out.push('\n');
        }
        out.push_str(&pad);
        out.push_str(line);
    }
    out
}

fn split_image(image: &str) -> (String, String) {
    match image.rsplit_once(':') {
        Some((repo, tag)) if !repo.is_empty() && !tag.contains('/') => {
            (repo.to_owned(), tag.to_owned())
        }
        _ => (image.to_owned(), "latest".to_owned()),
    }
}

fn named_ports(process: &ResolvedProcess) -> Vec<NamedPort> {
    let mut ports = Vec::new();
    let mut seen = std::collections::BTreeSet::new();
    for endpoint in &process.listens {
        if let Some(port) = port_of(&endpoint.address)
            && seen.insert(port)
        {
            ports.push(NamedPort {
                name: port_name(&endpoint.name),
                port,
            });
        }
    }
    if let Some(serve) = &process.serve
        && let Some(port) = port_of(&serve.listen_addr)
        && seen.insert(port)
    {
        ports.push(NamedPort {
            name: "http".to_owned(),
            port,
        });
    }
    ports
}

fn port_of(address: &str) -> Option<u16> {
    address.rsplit(':').next()?.parse().ok()
}

fn port_name(raw: &str) -> String {
    let name: String = raw
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '-' })
        .collect();
    if name.is_empty() {
        "http".to_owned()
    } else {
        name
    }
}

fn rest_prefix(input: &GenerateInput<'_>, process: &ResolvedProcess) -> String {
    if !matches!(process.kind, ProcessKind::Host) {
        return String::new();
    }
    let Some(id) = &process.rest_host else {
        return String::new();
    };
    let Some(gear) = input.lock.gears.get(id) else {
        return String::new();
    };
    let Some(serde_json::Value::String(raw)) = gear.config.get("prefix_path") else {
        return String::new();
    };
    let trimmed = raw.trim().trim_matches('/');
    if trimmed.is_empty() {
        String::new()
    } else {
        format!("/{trimmed}")
    }
}

fn probe_path(prefix: &str, route: &str) -> String {
    if prefix.is_empty() {
        route.to_owned()
    } else {
        format!("{prefix}{route}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn helm_delimiters_leave_mustache_intact() {
        let source = templates::TemplateSet::builtin("helm/helpers.tpl").expect("builtin");
        let rendered = templates::render_helm(
            "helm/helpers.tpl",
            source,
            context! { name => "api-gateway", uid => 65532u32 },
        )
        .expect("render");
        assert!(
            rendered.contains("{{ include \"api-gateway.chart\" . }}"),
            "{rendered}"
        );
        assert!(rendered.contains("runAsUser: 65532"), "{rendered}");
        assert!(
            !rendered.contains("<<"),
            "`<<` survived into the Helm template:\n{rendered}"
        );
        assert!(
            rendered.contains("{{"),
            "Helm's `{{ }}` did not survive:\n{rendered}"
        );
    }

    #[test]
    fn split_image_uses_the_last_colon() {
        assert_eq!(
            split_image("registry.example.com/payments/gbx-api-gateway:0.1.0"),
            (
                "registry.example.com/payments/gbx-api-gateway".to_owned(),
                "0.1.0".to_owned()
            )
        );
        assert_eq!(
            split_image("localhost:5000/gbx-api-gateway"),
            (
                "localhost:5000/gbx-api-gateway".to_owned(),
                "latest".to_owned()
            )
        );
    }
}
