//! Helm umbrella chart: one subchart per process.
//!
//! Emitted only for a Kubernetes profile. Chart.yaml and values.yaml are
//! serialized data, not templates -- minijinja would turn a version string
//! into an accidental substitution, and "Template text. Serialize data" is
//! the rule this milestone exists to keep. The YAML *inside* `templates/`
//! is Helm, so minijinja runs with `<< >>` delimiters and leaves `{{ }}`
//! for Helm.
//!
//! Service names are the process/subchart names, not Helm fullnames.
//! `advertise_uri` in the lock is `http://{subchart}.{namespace}.svc...`;
//! a Service named `{release}-{name}` would be a DNS name nobody dials.
//! The cluster SDK is stricter still: if the process links the `cluster`
//! gear, a second Service is named exactly `cluster` on port 50051.
//!
//! Secrets never appear in values. `${VAR}` placeholders in the generated
//! config become `secretKeys`, and `secret_ref = "existingSecret:<name>"`
//! on a cluster binding becomes `existingSecret`. The chart injects those
//! names as `secretKeyRef` env; the operator's Secret holds the values.

use std::collections::{BTreeMap, BTreeSet};

use gearbox_ir::{FileEntry, FileKind, FileSet, Ownership, ProcessKind, ResolvedProcess};
use minijinja::context;
use serde::Serialize;

use super::paths;
use super::templates;
use super::{GenerateError, GenerateInput, K8S_HOME_DIR, NONROOT_UID, header};

const CLUSTER_SERVICE: &str = "cluster";
const CLUSTER_PORT: u16 = 50051;

#[derive(Serialize)]
struct NamedPort {
    name: String,
    port: u16,
}

/// Every Helm artefact for this lock, or none if the profile does not
/// generate a chart.
///
/// Reads each process's already-generated `config/<p>.yaml` out of `files`
/// so the `ConfigMap` carries the same bytes the binary will `--config`.
///
/// # Errors
/// Returns [`GenerateError`] when a template cannot render, a path is not
/// a valid relative path, or a process has no image under Kubernetes.
pub fn files(input: &GenerateInput<'_>, files: &FileSet) -> Result<Vec<FileEntry>, GenerateError> {
    if input.lock.kubernetes.is_none() {
        return Ok(Vec::new());
    }

    let product = input.lock.product.id.as_str();
    let version = input.lock.product.version.as_str();
    let mut out = Vec::new();

    out.push(umbrella_chart(input, product, version)?);
    out.extend(umbrella_values(input, files)?);
    out.push(umbrella_helpers(product)?);

    for process in &input.lock.processes {
        let sub = subchart_name(process);
        out.push(subchart_chart(product, sub, version)?);
        out.extend(subchart_templates(input, process, files)?);
    }
    Ok(out)
}

fn subchart_name(process: &ResolvedProcess) -> &str {
    process
        .subchart
        .as_deref()
        .unwrap_or_else(|| process.name.as_str())
}

fn umbrella_chart(
    input: &GenerateInput<'_>,
    product: &str,
    version: &str,
) -> Result<FileEntry, GenerateError> {
    let mut body = String::new();
    body.push_str(&header("#"));
    body.push_str("apiVersion: v2\n");
    body.push_str("name: ");
    body.push_str(product);
    body.push('\n');
    body.push_str("description: Generated gearbox chart; workloads live in charts/\n");
    body.push_str("type: application\n");
    body.push_str("version: \"");
    body.push_str(version);
    body.push_str("\"\n");
    body.push_str("appVersion: \"");
    body.push_str(version);
    body.push_str("\"\n");
    body.push_str("dependencies:\n");
    for process in &input.lock.processes {
        let sub = subchart_name(process);
        body.push_str("  - name: ");
        body.push_str(sub);
        body.push('\n');
        body.push_str("    version: \"");
        body.push_str(version);
        body.push_str("\"\n");
        body.push_str("    repository: \"file://charts/");
        body.push_str(sub);
        body.push_str("\"\n");
        body.push_str("    condition: ");
        body.push_str(sub);
        body.push_str(".enabled\n");
    }
    Ok(FileEntry::text(
        paths::rel(&["helm", product, "Chart.yaml"])?,
        body,
        FileKind::Yaml,
        Ownership::Generated,
    ))
}

fn subchart_chart(product: &str, sub: &str, version: &str) -> Result<FileEntry, GenerateError> {
    let mut body = String::new();
    body.push_str(&header("#"));
    body.push_str("apiVersion: v2\n");
    body.push_str("name: ");
    body.push_str(sub);
    body.push('\n');
    body.push_str("description: Process subchart generated by gearbox\n");
    body.push_str("type: application\n");
    body.push_str("version: \"");
    body.push_str(version);
    body.push_str("\"\n");
    body.push_str("appVersion: \"");
    body.push_str(version);
    body.push_str("\"\n");
    Ok(FileEntry::text(
        paths::rel(&["helm", product, "charts", sub, "Chart.yaml"])?,
        body,
        FileKind::Yaml,
        Ownership::Generated,
    ))
}

/// Umbrella values and the schema that constrains them.
///
/// `values.yaml` is [`Ownership::OperatorOwned`]: the first real consumer of
/// the three-way merge. Images and replica counts still start here so
/// `helm template` (which only auto-loads `values.yaml`) renders. A second
/// generate updates the image tag through merge3 while an operator's
/// `replicaCount` edit survives.
///
/// `values.generated.yaml` is the same bytes, always overwritten, so the
/// operator can diff what the lock decided from what they have kept.
/// Helm does not load it; passing `-f` is optional.
///
/// The merge base lives in `.gearbox/<product>/.base/`, shared across
/// profiles. Only Kubernetes emits this chart, so a `dev` generate cannot
/// clobber a `prod` operator file.
fn umbrella_values(
    input: &GenerateInput<'_>,
    files: &FileSet,
) -> Result<Vec<FileEntry>, GenerateError> {
    let mut blocks = BTreeMap::new();
    for process in &input.lock.processes {
        let (repository, tag) = split_image(process.image.as_deref().unwrap_or(&process.bin_name));
        let config_rel = paths::rel(&["config", &format!("{}.yaml", process.name)])?;
        let keys = files
            .get(&config_rel)
            .and_then(FileEntry::as_text)
            .map(secret_vars)
            .unwrap_or_default();
        blocks.insert(
            subchart_name(process).to_owned(),
            SubchartValues {
                enabled: true,
                replica_count: process.replicas,
                image: ImageValues {
                    repository,
                    tag,
                    pull_policy: "IfNotPresent".to_owned(),
                },
                service_account: ServiceAccountValues {
                    create: true,
                    name: None,
                },
                name_override: None,
                fullname_override: None,
                pod_annotations: None,
                node_selector: None,
                tolerations: None,
                affinity: None,
                resources: None,
                extra_env: None,
                extra_volumes: None,
                extra_volume_mounts: None,
                pod_security_context: None,
                existing_secret: existing_secret(process, input),
                secret_keys: if keys.is_empty() { None } else { Some(keys) },
            },
        );
    }
    let values = UmbrellaValues {
        global: None,
        subcharts: blocks,
    };
    let yaml = serde_saphyr::to_string(&values).map_err(|source| GenerateError::Yaml {
        what: "helm values.yaml",
        source,
    })?;
    let body = format!("{}\n{yaml}", header("#"));
    let product = input.lock.product.id.as_str();
    Ok(vec![
        FileEntry::text(
            paths::rel(&["helm", product, "values.yaml"])?,
            body.clone(),
            FileKind::Yaml,
            Ownership::OperatorOwned,
        ),
        FileEntry::text(
            paths::rel(&["helm", product, "values.generated.yaml"])?,
            body,
            FileKind::Yaml,
            Ownership::Generated,
        ),
        values_schema(input)?,
    ])
}

/// JSON Schema for the umbrella values, with `additionalProperties: false`.
///
/// Top-level keys are the process/subchart names, which vary per product, so
/// the root object is assembled here rather than derived from one struct.
/// The per-subchart shape comes from [`schemars`] so the schema and the
/// values we serialize cannot drift by a field someone added to one side.
fn values_schema(input: &GenerateInput<'_>) -> Result<FileEntry, GenerateError> {
    let subchart = draft7_subchart_schema()?;
    let mut properties = serde_json::Map::new();
    properties.insert("global".to_owned(), global_schema());
    let mut required = Vec::new();
    for process in &input.lock.processes {
        let name = subchart_name(process);
        properties.insert(name.to_owned(), subchart.clone());
        required.push(serde_json::Value::String(name.to_owned()));
    }
    let schema = serde_json::json!({
        "$schema": "http://json-schema.org/draft-07/schema#",
        "$comment": format!(
            "GENERATED by gearbox {} -- do not edit. Run `gearbox generate` to regenerate.",
            env!("CARGO_PKG_VERSION")
        ),
        "type": "object",
        "additionalProperties": false,
        "properties": properties,
        "required": required,
    });
    let body = serde_json::to_string_pretty(&schema).map_err(|source| GenerateError::Json {
        what: "values.schema.json",
        source,
    })?;
    Ok(FileEntry::text(
        paths::rel(&["helm", input.lock.product.id.as_str(), "values.schema.json"])?,
        format!("{body}\n"),
        FileKind::Json,
        Ownership::Generated,
    ))
}

/// Helm's validator is draft-07 (`definitions`, not `$defs`) and does not
/// follow `$ref` the way schemars 1 emits it. Inline the `$defs` so the
/// schema we hand Helm is a tree of `type`/`properties` only.
fn draft7_subchart_schema() -> Result<serde_json::Value, GenerateError> {
    let mut raw =
        serde_json::to_value(schemars::schema_for!(SubchartValues)).map_err(|source| {
            GenerateError::Json {
                what: "the subchart values schema",
                source,
            }
        })?;
    let defs = raw
        .as_object_mut()
        .and_then(|object| object.remove("$defs"))
        .unwrap_or_else(|| serde_json::json!({}));
    if let Some(object) = raw.as_object_mut() {
        object.remove("$schema");
        object.remove("title");
        object.remove("description");
    }
    inline_refs(&mut raw, &defs);
    // Helm copies `global` onto every subchart's values. Refusing it would
    // make `helm template` fail on a chart that did not set global at all.
    if let Some(properties) = raw.get_mut("properties").and_then(|p| p.as_object_mut()) {
        properties.insert("global".to_owned(), serde_json::json!({ "type": "object" }));
    }
    Ok(raw)
}

fn global_schema() -> serde_json::Value {
    serde_json::json!({
        "type": "object",
        "additionalProperties": false,
        "properties": {
            "imageRegistry": { "type": "string" },
            "imagePullSecrets": {
                "type": "array",
                "items": { "type": "string" }
            }
        }
    })
}

fn inline_refs(value: &mut serde_json::Value, defs: &serde_json::Value) {
    match value {
        serde_json::Value::Object(map) => {
            if let Some(serde_json::Value::String(reference)) = map.get("$ref")
                && let Some(name) = reference.strip_prefix("#/$defs/")
                && let Some(def) = defs.get(name)
            {
                *value = def.clone();
                inline_refs(value, defs);
                return;
            }
            for nested in map.values_mut() {
                inline_refs(nested, defs);
            }
        }
        serde_json::Value::Array(items) => {
            for nested in items {
                inline_refs(nested, defs);
            }
        }
        _ => {}
    }
}

/// Shared by the values files (serde) and `values.schema.json` (schemars),
/// so a field cannot appear in one and not the other.
///
/// Optional hatches are omitted from the default YAML so a first generate
/// stays small, but they stay in the schema so `--set` of an unknown key
/// still fails and a documented hatch still type-checks.
#[derive(serde::Serialize, schemars::JsonSchema)]
#[serde(rename_all = "camelCase")]
#[schemars(deny_unknown_fields)]
struct SubchartValues {
    enabled: bool,
    replica_count: u32,
    image: ImageValues,
    service_account: ServiceAccountValues,
    #[serde(skip_serializing_if = "Option::is_none")]
    name_override: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    fullname_override: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pod_annotations: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    node_selector: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    tolerations: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    affinity: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    resources: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    extra_env: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    extra_volumes: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    extra_volume_mounts: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pod_security_context: Option<serde_json::Value>,
    /// Name of a Secret the operator already created. Never a credential.
    #[serde(skip_serializing_if = "Option::is_none")]
    existing_secret: Option<String>,
    /// Env names taken from `${VAR}` placeholders in this process's config.
    #[serde(skip_serializing_if = "Option::is_none")]
    secret_keys: Option<Vec<String>>,
}

#[derive(serde::Serialize)]
struct UmbrellaValues {
    #[serde(skip_serializing_if = "Option::is_none")]
    global: Option<GlobalValues>,
    #[serde(flatten)]
    subcharts: BTreeMap<String, SubchartValues>,
}

#[derive(serde::Serialize, schemars::JsonSchema)]
#[serde(rename_all = "camelCase")]
#[schemars(deny_unknown_fields)]
struct GlobalValues {
    #[serde(skip_serializing_if = "Option::is_none")]
    image_registry: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    image_pull_secrets: Option<Vec<String>>,
}

#[derive(serde::Serialize, schemars::JsonSchema)]
#[serde(rename_all = "camelCase")]
#[schemars(deny_unknown_fields)]
struct ImageValues {
    repository: String,
    tag: String,
    pull_policy: String,
}

#[derive(serde::Serialize, schemars::JsonSchema)]
#[serde(rename_all = "camelCase")]
#[schemars(deny_unknown_fields)]
struct ServiceAccountValues {
    create: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    name: Option<String>,
}

fn umbrella_helpers(product: &str) -> Result<FileEntry, GenerateError> {
    Ok(FileEntry::text(
        paths::rel(&["helm", product, "templates", "_helpers.tpl"])?,
        format!(
            "{{{{/* GENERATED by gearbox {} -- do not edit. Workloads live in charts/. */}}}}\n",
            env!("CARGO_PKG_VERSION")
        ),
        FileKind::Text,
        Ownership::Generated,
    ))
}

fn subchart_templates(
    input: &GenerateInput<'_>,
    process: &ResolvedProcess,
    files: &FileSet,
) -> Result<Vec<FileEntry>, GenerateError> {
    let product = input.lock.product.id.as_str();
    let name = subchart_name(process);
    let config_filename = format!("{}.yaml", process.name);
    let config_rel = paths::rel(&["config", &config_filename])?;
    let config_raw = files
        .get(&config_rel)
        .and_then(FileEntry::as_text)
        .ok_or_else(|| GenerateError::BadPath {
            path: config_rel.as_str().to_owned(),
        })?;
    let config_yaml = indent_block(config_raw, 4);

    let ports = named_ports(process);
    let http_port = process
        .service_port
        .or_else(|| ports.first().map(|p| p.port))
        .unwrap_or(80);
    let prefix = rest_prefix(input, process);
    let liveness_path = probe_path(&prefix, "/healthz");
    let readiness_path = probe_path(&prefix, "/readyz");
    let cluster_service = process.gears.iter().any(|g| g.as_str() == CLUSTER_SERVICE);

    let common = context! {
        name => name,
        process => process.name.as_str(),
        uid => NONROOT_UID,
    };

    let helpers = templates::render_helm(
        "helm/helpers.tpl",
        input.templates.get("helm/helpers.tpl")?,
        common,
    )?;
    let deployment = templates::render_helm(
        "helm/deployment.yaml",
        input.templates.get("helm/deployment.yaml")?,
        context! {
            name => name,
            process => process.name.as_str(),
            config_filename => config_filename.as_str(),
            http_port => http_port,
            liveness_path => liveness_path.as_str(),
            readiness_path => readiness_path.as_str(),
            uid => NONROOT_UID,
            home_dir => K8S_HOME_DIR,
            container_ports => &ports,
        },
    )?;
    let service = templates::render_helm(
        "helm/service.yaml",
        input.templates.get("helm/service.yaml")?,
        context! {
            name => name,
            service_name => name,
            ports => &ports,
            cluster_service => cluster_service,
            cluster_port => CLUSTER_PORT,
        },
    )?;
    let configmap = templates::render_helm(
        "helm/configmap.yaml",
        input.templates.get("helm/configmap.yaml")?,
        context! {
            name => name,
            config_filename => config_filename.as_str(),
            config_yaml => config_yaml.as_str(),
        },
    )?;
    let serviceaccount = templates::render_helm(
        "helm/serviceaccount.yaml",
        input.templates.get("helm/serviceaccount.yaml")?,
        context! { name => name },
    )?;

    let base = |file: &str| -> Result<_, GenerateError> {
        paths::rel(&["helm", product, "charts", name, "templates", file])
    };
    Ok(vec![
        FileEntry::text(
            base("_helpers.tpl")?,
            helpers,
            FileKind::Text,
            Ownership::Generated,
        ),
        FileEntry::text(
            base("deployment.yaml")?,
            deployment,
            FileKind::Yaml,
            Ownership::Generated,
        ),
        FileEntry::text(
            base("service.yaml")?,
            service,
            FileKind::Yaml,
            Ownership::Generated,
        ),
        FileEntry::text(
            base("configmap.yaml")?,
            configmap,
            FileKind::Yaml,
            Ownership::Generated,
        ),
        FileEntry::text(
            base("serviceaccount.yaml")?,
            serviceaccount,
            FileKind::Yaml,
            Ownership::Generated,
        ),
    ])
}

fn indent_block(text: &str, spaces: usize) -> String {
    let pad = " ".repeat(spaces);
    let mut out = String::new();
    for (i, line) in text.lines().enumerate() {
        if i > 0 {
            out.push('\n');
        }
        out.push_str(&pad);
        out.push_str(line);
    }
    out
}

/// Env names the runtime will try to expand out of this process's config.
///
/// Scanned from the generated YAML rather than from a field table, because
/// the postgres plugin, toolkit-db and static-credstore all share `${VAR}`
/// / `${VAR:-default}` and the `ConfigMap` is what the binary actually loads.
/// A placeholder the process will not expand is still harmless as env.
fn secret_vars(config: &str) -> Vec<String> {
    let mut found = BTreeSet::new();
    let mut rest = config;
    while let Some(start) = rest.find("${") {
        rest = &rest[start + 2..];
        let Some(end) = rest.find('}') else {
            break;
        };
        let inner = &rest[..end];
        let name = inner.split_once(':').map_or(inner, |(name, _)| name);
        if is_env_name(name) {
            found.insert(name.to_owned());
        }
        rest = &rest[end + 1..];
    }
    found.into_iter().collect()
}

fn is_env_name(name: &str) -> bool {
    let mut chars = name.chars();
    match chars.next() {
        Some(c) if c.is_ascii_uppercase() || c == '_' => {
            chars.all(|c| c.is_ascii_uppercase() || c.is_ascii_digit() || c == '_')
        }
        _ => false,
    }
}

/// `secret_ref = "existingSecret:<name>"` is the lock spelling of a Secret
/// the operator already created. Any other shape stays in config only:
/// a vault path is not a Kubernetes object name.
fn existing_secret(process: &ResolvedProcess, input: &GenerateInput<'_>) -> Option<String> {
    input.lock.cluster.iter().find_map(|binding| {
        if !binding.requesters.iter().any(|gear| process.contains(gear)) {
            return None;
        }
        binding
            .secret_ref
            .as_deref()?
            .strip_prefix("existingSecret:")
            .filter(|name| !name.is_empty())
            .map(str::to_owned)
    })
}

fn split_image(image: &str) -> (String, String) {
    match image.rsplit_once(':') {
        Some((repo, tag)) if !repo.is_empty() && !tag.contains('/') => {
            (repo.to_owned(), tag.to_owned())
        }
        _ => (image.to_owned(), "latest".to_owned()),
    }
}

fn named_ports(process: &ResolvedProcess) -> Vec<NamedPort> {
    let mut ports = Vec::new();
    let mut seen = std::collections::BTreeSet::new();
    for endpoint in &process.listens {
        if let Some(port) = port_of(&endpoint.address)
            && seen.insert(port)
        {
            ports.push(NamedPort {
                name: port_name(&endpoint.name),
                port,
            });
        }
    }
    if let Some(serve) = &process.serve
        && let Some(port) = port_of(&serve.listen_addr)
        && seen.insert(port)
    {
        ports.push(NamedPort {
            name: "http".to_owned(),
            port,
        });
    }
    ports
}

fn port_of(address: &str) -> Option<u16> {
    address.rsplit(':').next()?.parse().ok()
}

fn port_name(raw: &str) -> String {
    let name: String = raw
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '-' })
        .collect();
    if name.is_empty() {
        "http".to_owned()
    } else {
        name
    }
}

fn rest_prefix(input: &GenerateInput<'_>, process: &ResolvedProcess) -> String {
    if !matches!(process.kind, ProcessKind::Host) {
        return String::new();
    }
    let Some(id) = &process.rest_host else {
        return String::new();
    };
    let Some(gear) = input.lock.gears.get(id) else {
        return String::new();
    };
    let Some(serde_json::Value::String(raw)) = gear.config.get("prefix_path") else {
        return String::new();
    };
    let trimmed = raw.trim().trim_matches('/');
    if trimmed.is_empty() {
        String::new()
    } else {
        format!("/{trimmed}")
    }
}

fn probe_path(prefix: &str, route: &str) -> String {
    if prefix.is_empty() {
        route.to_owned()
    } else {
        format!("{prefix}{route}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn helm_delimiters_leave_mustache_intact() {
        let source = templates::TemplateSet::builtin("helm/helpers.tpl").expect("builtin");
        let rendered = templates::render_helm(
            "helm/helpers.tpl",
            source,
            context! { name => "api-gateway", uid => 65532u32 },
        )
        .expect("render");
        assert!(
            rendered.contains("{{ include \"api-gateway.chart\" . }}"),
            "{rendered}"
        );
        assert!(rendered.contains("runAsUser: 65532"), "{rendered}");
        assert!(
            !rendered.contains("<<"),
            "`<<` survived into the Helm template:\n{rendered}"
        );
        assert!(
            rendered.contains("{{"),
            "Helm's `{{ }}` did not survive:\n{rendered}"
        );
    }

    #[test]
    fn split_image_uses_the_last_colon() {
        assert_eq!(
            split_image("registry.example.com/payments/gbx-api-gateway:0.1.0"),
            (
                "registry.example.com/payments/gbx-api-gateway".to_owned(),
                "0.1.0".to_owned()
            )
        );
        assert_eq!(
            split_image("localhost:5000/gbx-api-gateway"),
            (
                "localhost:5000/gbx-api-gateway".to_owned(),
                "latest".to_owned()
            )
        );
    }

    #[test]
    fn secret_vars_reads_plain_and_defaulted_placeholders() {
        let config = "connection_string: postgres://u:${PG_PASSWORD}@${PG_HOST:-db}/payments\n\
                      token: ${not_an_env}\n\
                      other: ${i}\n";
        assert_eq!(
            secret_vars(config),
            vec!["PG_HOST".to_owned(), "PG_PASSWORD".to_owned()]
        );
    }
}
